Quintenv driel/issue3
AIDDEI/life-below-water pull request #25
Opened 2023-05-24 12:46 UTC by QuintenvDriel

- Klok (timer) toegevoegd aan game
- Begin van TO DO list aangemaakt

2023-05-24 17:38 UTC, Isissss commented
Is het af of nog niet?

2023-05-31 12:00 UTC, QuintenvDriel reviewed
digitale clock is veranderd naar analoog die 15 min verspringt(niet binnen het canvas kunnen krijgen). Er is een knop die een lijst met uitgoerde taken laat zien!

2023-05-31 14:03 UTC, Isissss commented
De code werkt nog niet zo te zien, klopt dat?

ook maak je nu twee keer een pixi application aan, dit hoef je niet te doen. Je kan de click in een class zetten die extend van PIXI.Container. Daarin genereer je de content.

2023-05-31 14:13 UTC, Isissss requested changes

2023-05-31 14:13 UTC, Isissss commented on .idea/vcs.xml
Verwijder aub alles in .idea en voeg .idea toe in de global .gitignore

2023-05-31 14:13 UTC, Isissss commented on src/AssetLoader.ts
> +import ToDoImage from "./images/to do button.png"
in de toekomst zal i kgeen spaties gebruiken in namen van images

2023-05-31 14:13 UTC, Isissss commented on src/ToDoMenu.ts
> +    const taskList = ['Taak 1', 'Taak 2', 'Taak 3'];
Je hebt hierdoor niet de mogelijkheid om tasks to te voegen. Dit zou je beter in de contructor kunnen zetten, en de loop veranderen naar const task of this.taskList

2023-05-31 14:13 UTC, Isissss commented on src/clock.ts
> +    height: 400, // Hoogte van het canvas
Lees laatste comment voor review, niet nodig om een nieuwe applicatie aan te maken.

2023-05-31 14:13 UTC, Isissss commented on src/clock.ts
> +});
Er mist nog een functie om de tijd te verzetten. Nu kan dit alleen via een click, kijk of je ook een funcite kan toevoegen om dit via een method te doen.

2023-05-31 14:13 UTC, Isissss commented on src/game.ts
> +import { Clock } from './clock';
zorg dat de file een hoofdletter heeft

2023-05-31 14:13 UTC, Isissss commented on src/game.ts
> +    this.toDoButton.buttonMode = true;
Dit is deprecated. Het is nu "eventmode = "static"  ipv interactive en buttonMode

2023-05-31 14:13 UTC, Isissss commented on src/game.ts
> +    this.toDoButton.on('click', () => {
Dit lijkt me beter in de todobutton class zelf :)

2023-06-12 11:26 UTC, closed without merging