QuintenvDriel/issue1
AIDDEI/life-below-water pull request #31
Opened 2023-05-31 11:53 UTC by QuintenvDriel

(compleet) er is een knop aangemaakt die een menu met tips en leerzame opmerkingen kan laten zien.

2023-05-31 11:54 UTC, QuintenvDriel commented
(compleet) er is een knop toegevoegd die een menu met leerzame tips en opmerkingen kan laten zien!

2023-06-12 11:52 UTC, Isissss requested changes

2023-06-12 11:52 UTC, Isissss commented on src/clock.ts
> +    // this.on('pointerdown', () => {
remove comments

2023-06-12 11:52 UTC, Isissss commented on src/clock.ts
> +  public getContainer(): PIXI.Container {
haal functie weg, niet nodig

2023-06-12 11:52 UTC, Isissss commented on src/index.html
> +    <link rel="stylesheet" type="text/css" href="style.css">
Is dit echt nodig of niet

2023-06-12 11:52 UTC, Isissss commented on src/clock.ts
> +  public shiftClock() {
kan je hier een funcite maken dat de klok ook meer dan 15 min per keer kan worden verschoven

2023-06-12 13:30 UTC, Isissss approved these changes

2023-06-12 13:39 UTC, merged